---
- name: Установить HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Разложить конфигурацию HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: restart haproxy

- name: Проверить конфигурацию до запуска
  ansible.builtin.command: haproxy -c -f /etc/haproxy/haproxy.cfg
  changed_when: false

- name: Включить HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
