apiVersion: v1
kind: Service
metadata:
  name: night-shift-metallb
  namespace: traffic-lab
  labels:
    app.kubernetes.io/name: night-shift
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: night-shift
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
