apiVersion: v1
kind: Secret
metadata:
  name: devops-may-cry-db
  namespace: traffic-lab
type: Opaque
stringData:
  POSTGRES_DB: devopsmaycry
  POSTGRES_USER: devopsmaycry
  POSTGRES_PASSWORD: REPLACE_BEFORE_APPLY
