#!/usr/bin/env python3
"""Build deterministic recording artifacts from hand-curated command decks.

The presenter-facing teleprompter is generated from a prose template. Command
blocks are injected from the matching commands/VIDEO2_PARTN_COMMANDS.md by
stable IDs, so a command cannot silently diverge between the copy deck and the
teleprompter.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
PARTS = (1, 2, 3, 4)

HEADING_RE = re.compile(
    r"^## (?P<id>V2-C[1-4]-S\d{2}-C\d{2}) · (?P<title>.+)$", re.MULTILINE
)
MARKER_RE = re.compile(r"\{\{COMMAND:(V2-C[1-4]-S\d{2}-C\d{2})\}\}")


@dataclass(frozen=True)
class Command:
    command_id: str
    title: str
    shell: str
    expected: str


def parse_commands(markdown: str) -> dict[str, Command]:
    matches = list(HEADING_RE.finditer(markdown))
    commands: dict[str, Command] = {}
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(markdown)
        section = markdown[start:end].strip()
        fence = re.search(r"```bash\n(?P<shell>.*?)\n```", section, re.DOTALL)
        if not fence:
            raise SystemExit(f"{match['id']}: missing bash fence")
        tail = section[fence.end() :].strip()
        expected = tail.split("\n\n", 1)[0].strip()
        if not expected.startswith("Ожидаю"):
            raise SystemExit(f"{match['id']}: missing explicit expected result")
        command_id = match["id"]
        if command_id in commands:
            raise SystemExit(f"duplicate command ID: {command_id}")
        commands[command_id] = Command(
            command_id=command_id,
            title=match["title"].strip(),
            shell=fence["shell"].rstrip(),
            expected=expected,
        )
    if not commands:
        raise SystemExit("no command IDs found")
    return commands


def render_command(command: Command) -> str:
    return (
        f"### ⌨️ {command.command_id} · {command.title}\n\n"
        f"```bash\n{command.shell}\n```\n\n"
        f"### ✅ После команды\n\n{command.expected}"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--part",
        type=int,
        choices=PARTS,
        action="append",
        help="build only the selected part; may be repeated (default: all available parts)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the generated teleprompter is not current",
    )
    args = parser.parse_args()
    selected = tuple(dict.fromkeys(args.part or PARTS))
    total = 0
    built = 0
    for part in selected:
        command_deck = REPO_ROOT / "commands" / f"VIDEO2_PART{part}_COMMANDS.md"
        source_path = REPO_ROOT / "teleprompter" / "source" / f"VIDEO2_PART{part}_SOURCE.md"
        output_path = REPO_ROOT / "teleprompter" / f"VIDEO2_PART{part}.md"
        available = command_deck.is_file() and source_path.is_file()
        if not available:
            if args.part:
                raise SystemExit(f"part {part}: command deck or source is missing")
            continue
        commands = parse_commands(command_deck.read_text(encoding="utf-8"))
        for command in commands.values():
            syntax = subprocess.run(
                ["bash", "-n"],
                input=command.shell,
                text=True,
                capture_output=True,
                check=False,
            )
            if syntax.returncode != 0:
                raise SystemExit(
                    f"{command.command_id}: bash syntax failed\n{syntax.stderr.rstrip()}"
                )
        wrong_part = sorted(item for item in commands if not item.startswith(f"V2-C{part}-"))
        if wrong_part:
            raise SystemExit(f"part {part}: command IDs belong to another part: {wrong_part}")
        source = source_path.read_text(encoding="utf-8")
        markers = MARKER_RE.findall(source)
        missing = sorted(set(commands) - set(markers))
        unknown = sorted(set(markers) - set(commands))
        duplicate_markers = sorted({item for item in markers if markers.count(item) > 1})
        if missing or unknown or duplicate_markers:
            raise SystemExit(
                f"part {part}: teleprompter/command contract failed\n"
                f"missing markers: {missing}\n"
                f"unknown markers: {unknown}\n"
                f"duplicate markers: {duplicate_markers}"
            )

        rendered = MARKER_RE.sub(lambda m: render_command(commands[m.group(1)]), source)
        generated_header = (
            "<!-- GENERATED by scripts/build-recording-artifacts.py. "
            f"Edit {source_path.relative_to(REPO_ROOT)} and "
            f"{command_deck.relative_to(REPO_ROOT)}. -->\n\n"
        )
        result = generated_header + rendered.rstrip() + "\n"
        if args.check:
            current = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
            if current != result:
                raise SystemExit(
                    f"part {part}: generated teleprompter is stale; "
                    f"run scripts/build-recording-artifacts.py --part {part}"
                )
            print(f"part {part} recording contract OK: {len(commands)} command blocks")
        else:
            output_path.write_text(result, encoding="utf-8")
            print(f"built {output_path.relative_to(REPO_ROOT)}: {len(commands)} command blocks")
        total += len(commands)
        built += 1
    if built == 0:
        raise SystemExit("no complete recording parts found")
    print(f"recording contract total: {total} command blocks across {built} part(s)")


if __name__ == "__main__":
    main()
