---
- name: Установить keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Установить healthcheck HAProxy
  ansible.builtin.copy:
    dest: /usr/local/sbin/check-video2-haproxy
    mode: '0755'
    content: |
      #!/usr/bin/env bash
      systemctl is-active --quiet haproxy

- name: Разложить конфигурацию keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: restart keepalived

- name: Включить keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: started
    enabled: true
